FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

RUN chmod +x tools/docker-entrypoint.dev.sh

CMD ["./tools/docker-entrypoint.dev.sh"]
