FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN pnpm install

COPY . .

RUN sed -i 's/\r$//' tools/docker-entrypoint.dev.sh && chmod +x tools/docker-entrypoint.dev.sh

CMD ["./tools/docker-entrypoint.dev.sh"]
